name: Deploy Web2 to Oracle

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            sudo mkdir -p /var/www/web2.com/public_html
            sudo chown -R ubuntu:ubuntu /var/www/web2.com
            cd /var/www/web2.com/public_html

            if [ ! -d ".git" ]; then
              git init
              git remote add origin https://github.com/Artazzz/web2-app.git
              git fetch origin main
              git checkout -t origin/main
            else
              git fetch origin main
              git reset --hard origin/main
            fi

            sudo nginx -t
            sudo systemctl reload nginx
